---
title: "HSCL Collections vs. Peer Institutions"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: spacelab
    social: menu
    source_code: https://github.com/ufhscl/collection-comparison/index.Rmd
---

```{r setup, include = FALSE}
library(tidyverse)
library(plotly)
library(DT)

collections_data <- readRDS("collections_data.Rdata")
```

```{r}
resource_data <- collections_data %>%
  select(!one_of("school", "code", "region")) %>%
  distinct()

rank_data <- collections_data %>% 
  count(resource) %>%
  arrange(desc(n)) %>%
  mutate(rank = row_number()) %>%
  select(!n)

summary_count <- collections_data %>%
  count(resource, region) %>%
  complete(resource, region, fill = list(n = 0)) %>%
  left_join(rank_data) %>%
  arrange(rank) %>%
  left_join(resource_data)

peer_data <- collections_data %>%
  group_by(school) %>%
  summarize(num_resources = n(), 
            resources = list(resource)) %>%
  left_join(distinct(select(collections_data, school, region))) %>%
  select(school, region, num_resources, resources) %>%
  arrange(desc(num_resources))

resource_info <- summary_count %>%
  pivot_wider(names_from = region, values_from = n) %>%
  left_join(resource_data) %>%
  mutate("Total peers with" = Florida + US, 
         "Florida peers with" = Florida, 
         "US peers with" = US) %>%
  select(!one_of("Florida", "US", "rank")) %>%
  select(resource, "Total peers with", "Florida peers with", "US peers with", everything())

backfiles <- resource_info %>%
  filter(onetime_purchase) %>%
  pull(resource)

```

Visualizations
===================================== 

Column {.tabset .storyboard}
-------------------------------------

### Florida Peers (no backfiles)

```{r}
to_plot <- summary_count %>%
  filter(region == "Florida", 
         !resource %in% backfiles)

p <- ggplot(to_plot, 
            aes(x = n, y = reorder(resource, n), fill = type)) + 
  geom_col() + 
  scale_x_continuous(breaks = seq(0, max(resource_info$`Total peers with`), by = 2)) + 
  theme_bw() + 
  labs(x = "# of Peer Institutions", y = "Resource Name")

ggplotly(p)
```   

### US Peers (no backfiles)

```{r}
to_plot <- summary_count %>%
  filter(region == "US", 
         !resource %in% backfiles)

p <- ggplot(to_plot, 
            aes(x = n, y = reorder(resource, n), fill = type)) + 
  geom_col() + 
  scale_x_continuous(breaks = seq(0, max(resource_info$`Total peers with`), by = 2)) + 
  theme_bw() + 
  labs(x = "# of Peer Institutions", y = "Resource Name")

ggplotly(p)
```

### All Peers (no backfiles)

```{r}
to_plot <- summary_count %>%
  filter(!resource %in% backfiles)

p <- ggplot(to_plot, 
            aes(x = n, y = reorder(resource, n), fill = type)) + 
  geom_col() + 
  scale_x_continuous(breaks = seq(0, max(resource_info$`Total peers with`), by = 2)) + 
  theme_bw() + 
  labs(x = "# of Peer Institutions", y = "Resource Name")

ggplotly(p)
```

### All Peers (inc. backfiles)

```{r}
p <- ggplot(summary_count, 
            aes(x = n, y = reorder(resource, n), fill = type)) + 
  geom_col() + 
  scale_x_continuous(breaks = seq(0, max(resource_info$`Total peers with`), by = 2)) + 
  theme_bw() + 
  labs(x = "# of Peer Institutions", y = "Resource Name")

ggplotly(p)
```

Peer Institution Data {data-navmenu="Data Tables"}
=====================================

Column {data-width=800}
-----------------------------------------------------------------------

```{r}
datatable(peer_data, 
          rownames = FALSE, 
          options = list(pageLength = NROW(peer_data), 
                         scrollY = "800px"))
```



Resource Data {data-navmenu="Data Tables"}
===================================== 

Column {data-width=800}
-----------------------------------------------------------------------

```{r}
datatable(resource_info, 
          rownames = FALSE, 
          options = list(pageLength = NROW(resource_info), 
                         scrollY = "800px"))
```


